[project]
name = "test-quarto-blog-ghp"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tyler Erickson <tyler@vorgeo.com>"]
channels = ["conda-forge"]
# linux-64 is used by GitHub Actions
platforms = ["osx-arm64", "linux-64"]

[tasks]

[dependencies]
python = "3.11.9.*"
jupyter = ">=1.0.0,<1.1"
numpy = ">=1.26.4,<1.27"
matplotlib = ">=3.8.4,<3.9"
